# Generated by Django 2.2.24 on 2023-05-07 13:32

from django.db import migrations


def transfer_owner_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        owner, _ = Owner.objects.get_or_create(name=flat.owner,
                                               phonenumber=flat.owners_phonenumber,
                                               pure_phone=flat.owner_pure_phone)
        owner.flats.add(flat)
        owner.save()


def backward_transfer_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230507_2332'),
    ]

    operations = [
        migrations.RunPython(transfer_owner_from_flat, backward_transfer_owner)
    ]