# Generated by Django 2.2.24 on 2023-05-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230508_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
